title: KW Sport Racing
shorttitle: KSR

project_name: KW Sport Racing
description: >
  KW Sport Racing motorcycle track days in Ontario. KW Sport Racing Club / KW Sport Riding Club runs track days exclusively at Grand Bend Motorplex. Join us for our 2019 Track Days!
repository_url: https://github.com/kwsportracing/site
repository_shorthand: kwsportracing/site

book_it: View our 2019 Track Days!
link_to_book: /dates/
registration: https://docs.google.com/forms/d/e/1FAIpQLSfXxoXyAZj-RoIbvjBm7NQ-eV_sfsFmA6GQai8sVlSCH0KQDw/viewform

facebook: https://www.facebook.com/groups/KWSportRacing/
youtube: https://www.youtube.com/watch?v=04iVIVKCyrg
instagram: https://www.instagram.com/kwsportracing/

home_url: http://kwsportracing.com

author_name: Copyright ©2019 KW Sport Racing
author_url: https://github.com/kwsportracing/site/graphs/contributors

url: https://kwsportracing.ca

license: KW Sport Racing is an Apache 2.0 project.
copyright: Copyright ©2019 KW Sport Racing

markdown: kramdown

docs_index: /getting-started

plugins:
  - jekyll-redirect-from

base_url: /
