title: KW Sport Racing

project_name: KW Sport Racing
description: >
  KW Sport Racing Motorcycle Track Days in Ontario Canada
repository_url: https://github.com/cdrage/kwsportracing
repository_shorthand: cdrage/kwsportracing

registration: https://docs.google.com/forms/d/e/1FAIpQLSfXxoXyAZj-RoIbvjBm7NQ-eV_sfsFmA6GQai8sVlSCH0KQDw/viewform

facebook: https://www.facebook.com/groups/KWSportRacing/

home_url: http://kwsportracing.com

author_name: Copyright ©2019 KW Sport Racing
author_url: https://github.com/cdrage/kwsportracing/graphs/contributors

url: http://charliedrage.com/kwsportracing/

license: KW Sport Racing is an Apache 2.0 project.
copyright: Copyright ©2019 KW Sport Racing

markdown: kramdown

docs_index: /getting-started

plugins:
  - jekyll-redirect-from

base_url: /kwsportracing
